name: uwalls
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+240701

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  email_validator: ^3.0.0
  cupertino_icons: ^1.0.6
  cloud_firestore: ^5.0.2
  adaptive_theme: ^3.6.0
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  smooth_corner: ^1.1.0
  fluttertoast: ^8.2.6
  google_fonts: ^6.2.1
  iconsax_plus: ^1.0.0
  dio: ^5.4.3+1
  get: ^4.6.6
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/
