// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_jLZdIf4fSDM-SKgVFuKIH-EMowLC2-4',
    appId: '1:17404392645:web:2e016bd3126eb2d470acac',
    messagingSenderId: '17404392645',
    projectId: 'uwalls-caa87',
    authDomain: 'uwalls-caa87.firebaseapp.com',
    storageBucket: 'uwalls-caa87.appspot.com',
    measurementId: 'G-W9EDZGRYXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhtNMoX7KhXX2Qrx16eQt2lSnX4AgRzng',
    appId: '1:17404392645:android:20bf99b2d692ffb570acac',
    messagingSenderId: '17404392645',
    projectId: 'uwalls-caa87',
    storageBucket: 'uwalls-caa87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY_8k9oRljqZxs6nytJjmBy9CVk4FJ7NI',
    appId: '1:17404392645:ios:bc5cdc70a5c18d7370acac',
    messagingSenderId: '17404392645',
    projectId: 'uwalls-caa87',
    storageBucket: 'uwalls-caa87.appspot.com',
    iosClientId: '17404392645-hpiuneai66sgfcoaqupeicnejd23gncc.apps.googleusercontent.com',
    iosBundleId: 'com.dany.dev.uwalls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY_8k9oRljqZxs6nytJjmBy9CVk4FJ7NI',
    appId: '1:17404392645:ios:bc5cdc70a5c18d7370acac',
    messagingSenderId: '17404392645',
    projectId: 'uwalls-caa87',
    storageBucket: 'uwalls-caa87.appspot.com',
    iosClientId: '17404392645-hpiuneai66sgfcoaqupeicnejd23gncc.apps.googleusercontent.com',
    iosBundleId: 'com.dany.dev.uwalls',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_jLZdIf4fSDM-SKgVFuKIH-EMowLC2-4',
    appId: '1:17404392645:web:f1520153678651cd70acac',
    messagingSenderId: '17404392645',
    projectId: 'uwalls-caa87',
    authDomain: 'uwalls-caa87.firebaseapp.com',
    storageBucket: 'uwalls-caa87.appspot.com',
    measurementId: 'G-8SJVXCQX2S',
  );

}